### ISSUE TITLE
Discussion on Pruning the 0 Layers

### ISSUE THREAD

**Issue by AlumLuther** [RICE-EIC/Early-Bird-Tickets#1]
Hello! I may have found a bug in pruning. 

Take vgg16 as an example. I chose a pruned_ratio of 0.6, and obtained the following cfg_mask:
[55, 64, 'M', 128, 128, 'M', 256, 253, 239, 'M', 142, 28, 8, 'M', 0, 1, 387]
One conv layer is pruned to zero. Based on my understanding, you skip the zero layer, build a ‘vgg15’ network based on the rest 12 conv layers. Then, you conduct the pruning by filling in the new network’s weight, based on the origin network’s weight.

In code implementation, you use start_mask and end_mask to mark the selected input and output channels. End_mask is actually an element of cfg_mask, which marks the origin network’s selected channels. When you encounter a layer with 0 channel, you have to skip it. So, I guess your code:

> `if torch.sum(end_mask) == 0:`
> `continue`

is designed to do the job. This line of code is placed right after the judgement of conv/BN layer. However, end_mask is updated only in the end of BN layer pruning. This result in the phenomenon: once the end_mask is all 0, it never changes, and the pruning algorithm directly skips all layers and ends.

Actually, I don’t think you have conducted pruning on the layers after the 0 layer. This can be seen by breakpoint debugging on the last BN layer, which weights are all 0.5(initial value). In addition, you print each conv layer right after conducting pruning on it. However, layers after the 0 layer have no printed information. I think those layers remain the initial weight.

Hope to receive your reply. Maybe I have problem understanding the code, if so please point it out. Thank you very much for your attention.
Best regards

**Comment by ranery** [comment]
Hi, thanks for your careful checking, we have addressed this issue and updated results during rebuttal: this “plunge” issue can be fixed by applying a simple “protective pruning” heuristic on top of our current algorithm. Specifically, we stop pruning a layer, when its remaining channels after pruning become less than 10% of the original, for avoiding overly slimming this layer; meanwhile we (uniformly) prune other layers more to meet the overall pruning ratio. Experiments show that such a simple protective strategy can effectively eliminate the plunges as shown in the updated Figures 1-2, without incurring overhead.
````
bn = []
protective_thre = {}
bn_index = 0
for m in model.modules():
    if isinstance(m, nn.BatchNorm2d):
        bn_index += 1
        size = m.weight.data.shape[0]
        w = m.weight.data.abs().clone()
        # protective layer-wise threshold
        y, i = torch.sort(w)
        thre_index = int(size * 0.9) # protect top 10%
        protective_thre[bn_index] = y[thre_index]
        # remaining channels are needed to prune
        for item in y[:thre_index]:
            bn.append(item)
````
